In [1]:
import pandas as pd
r = pd.read_excel('all6600.xlsx')
r.head()

  LABEL                                            COMMENT
0    EP                            You are very beautiful.
1    OT                                   ðŸ˜€ðŸ˜€ðŸ˜€ðŸ˜€
2    EP                                               Nice
3    GM  Atali Sundar mam as bakuda jode nathi sobhati .
4    EP          Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ

# Hindi Labels Only

In [3]:
r =dataset[dataset['LABEL'].isin(['EP'])]
r.head()

   LABEL                                    COMMENT
0     EP                    You are very beautiful.
2     EP                                       Nice
4     EP  Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ
9     EP                                      Super
10    EP                               Supar comedy

In [7]:
import string
def clean_text(text):
       # text_nonpunct = [c for c in text if c not in string.punctuation]
        text_nonpunct ="".join([c for c in text if c not in string.punctuation])
        return text_nonpunct
    
r['comclean'] = r['COMMENT'].apply(lambda x: clean_text(x))
r.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,LABEL,COMMENT,comclean
0,EP,You are very beautiful.,You are very beautiful
2,EP,Nice,Nice
4,EP,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ
9,EP,Super,Super
10,EP,Supar comedy,Supar comedy

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
cv1 = CountVectorizer(analyzer=clean_text)

X = cv1.fit_transform(r['COMMENT'])
print(X.shape)

(2401, 241)

In [9]:
print(cv1.get_feature_names())

['\n', ' ', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '\x81', '\x8d', '\x8f', '\x90', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', 'ª', '«', '¬', '\xad', '®', '¯', '°', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '»', '¼', '½', '¾', '¿', 'Ã', 'Å', 'Ç', 'Ì', '×', 'à', 'á', 'â', 'ä', 'ï', 'ð', 'ñ', 'ô', 'đ', 'ĺ', 'Œ', 'œ', 'Š', 'š', 'Ÿ', 'Ž', 'ž', 'ƒ', 'ˆ', '˜', '̽', '͓', 'ँ', 'ं', 'ः', 'अ', 'आ', 'इ', 'ई', 'उ', 'ऊ', 'ए', 'ऐ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'च', 'छ', 'ज', 'झ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'प', 'फ', 'ब', 'भ', 'म', 'य', 'र', 'ल', 'व', 'श', 'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'े', 'ै', 'ो', 'ौ', '्', 'ज़', 'ड़', '।', 'ਂ', 'ਆ', 'ਕ', 'ਗ', 'ਜ', 'ਣ', 'ਦ', 'ਨ', 'ਪ', 'ਲ', 'ਵ', 'ਸ', 'ਹ', 'ਾ', 'ਿ', 'ੂ', 'ੇ', 'ੈ', 'ੰ', 'ઁ', 'ં', 'ઃ', 'અ', 'આ', 'ઇ', 'ઈ', 'ઉ', 'ઊ', 'એ', 'ઐ', 'ઑ', 'ઓ', 'ક', 'ખ', 'ગ', 'ઘ', 'ઙ', 'ચ', 'છ', 'જ', 'ઝ', 'ઞ', 'ટ', 'ઠ', 'ડ', 'ઢ', 'ણ', 'ત', 'થ', 'દ', 'ધ', 'ન', 'પ', 'ફ', 'બ', 'ભ', 'મ', 'ય', 'ર', 'લ', 'ળ', 'વ', 'શ', 'ષ', 'સ', 'હ', '઼', 'ા', 'િ', 'ી', 'ુ', 'ૂ', 'ૃ', 'ૅ', 'ે', 'ૈ', 'ૉ', 'ો', 'ૌ', '્', 'ૐ', '૦', '૧', '૨', '૩', '૪', '૫', '૬', '૭', '૮', '૯', '\u200c', '\u200d', '–', '—', '‘', '’', '‚', '“', '”', '„', '†', '‡', '•', '…', '‰', '‹', '›', '€', '₹', '℅', '™', 'ℹ', '√', '☑', '☮', '☹', '☺', '♂', '♥', '⚔', '⚘', '⚰', '✌', '✍', '✨', '❌', '❣', '❤', '️', '🇦', '🇨', '🇪', '🇮', '🇳', '🇶', '🌁', '🌏', '🌷', '🌸', '🌹', '🌺', '🌻', '🍺', '🍻', '🎀', '🎁', '🎂', '🎇', '🎉', '🎖', '🎙', '🎤', '🎥', '🎧', '🎩', '🎬', '🎵', '🎶', '🎼', '🏁', '🏆', '🏵', '🏹', '🏻', '🏼', '🏾', '👆', '👇', '👈', '👉', '👋', '👌', '👍', '👎', '👏', '👑', '👒', '👔', '👕', '👖', '👠', '👦', '👧', '👨', '👩', '👪', '👫', '💃', '💄', '💋', '💌', '💍', '💎', '💐', '💓', '💔', '💕', '💖', '💗', '💘', '💙', '💚', '💛', '💜', '💝', '💞', '💢', '💥', '💪', '💯', '📌', '📍', '📚', '📝', '🔝', '🔥', '🔪', '🔫', '🕉', '🕊', '🖤', '😀', '😁', '😂', '😃', '😄', '😅', '😆', '😇', '😉', '😊', '😋', '😌', '😍', '😎', '😑', '😒', '😓', '😔', '😕', '😗', '😘', '😚', '😛', '😜', '😝', '😞', '😟', '😠', '😡', '😢', '😣', '😤', '😥', '😩', '😫', '😭', '😮', '😰', '😱', '😲', '😳', '😴', '😵', '😷', '😻', '🙂', '🙃', '🙄', '🙋', '🙌', '🙏', '🚒', '🚗', '🚩', '🚶', '🚹', '🛐', '🤐', '🤓', '🤔', '🤗', '🤘', '🤝', '🤞', '🤟', '🤡', '🤣', '🤦', '🤩', '🤪', '🤯', '🤳', '🤴', '🤷', '🥀', '🥃', '🥇', '🥰', '🥳', '🥺', '🦁', '🧡']

In [11]:
import string
def clean_text(text):
        msg =['\x81', '\x8d', '\x8f', '\x90', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', 'ª', 
              '«', '¬', '\xad', '®', '¯', '°', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '»', '¼', 
              '½', '¾', '¿', 'Ã', 'Å', 'Ç', 'Ì', '×', 'à', 'á', 'â', 'ä', 'ï', 'ð', 'ñ', 'ô', 'đ', 
              'ĺ', 'Œ', 'œ', 'Š', 'š', 'Ÿ', 'Ž', 'ž', 'ƒ', 'ˆ', '˜', '̽', '͓', 'ँ', 'ं', 'ः', 'अ', 
              'आ', 'इ', 'ई', 'उ', 'ऊ', 'ए', 'ऐ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'च', 'छ', 'ज', 
              'झ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'प', 'फ', 'ब', 'भ', 'म', 'य',
              'र', 'ल', 'व', 'श', 'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'े', 'ै', 'ो', 'ौ', '्',
              'ज़', 'ड़', '।', 'ਂ', 'ਆ', 'ਕ', 'ਗ', 'ਜ', 'ਣ', 'ਦ', 'ਨ', 'ਪ', 'ਲ', 'ਵ', 'ਸ', 'ਹ', 'ਾ', 'ਿ',
              'ੂ', 'ੇ', 'ੈ', 'ੰ', 'ઁ', 'ં', 'ઃ', 'અ', 'આ', 'ઇ', 'ઈ', 'ઉ', 'ઊ', 'એ', 'ઐ', 'ઑ', 'ઓ', 'ક',
              'ખ', 'ગ', 'ઘ', 'ઙ', 'ચ', 'છ', 'જ', 'ઝ', 'ઞ', 'ટ', 'ઠ', 'ડ', 'ઢ', 'ણ', 'ત', 'થ', 'દ', 'ધ', 
              'ન', 'પ', 'ફ', 'બ', 'ભ', 'મ', 'ય', 'ર', 'લ', 'ળ', 'વ', 'શ', 'ષ', 'સ', 'હ', '઼', 'ા', 'િ', 'ી',
              'ુ', 'ૂ', 'ૃ', 'ૅ', 'ે', 'ૈ', 'ૉ', 'ો', 'ૌ', '્', 'ૐ', '૦', '૧', '૨', '૩', '૪', '૫', '૬', '૭', '૮', '૯', 
              '\u200c', '\u200d', '–', '—', '‘', '’', '‚', '“', '”', '„', '†', '‡', '•', '…', '‰', '‹', '›', '€', 
              '₹', '℅', '™', 'ℹ', '√', '☑', '☮', '☹', '☺', '♂', '♥', '⚔', '⚘', '⚰', '✌', '✍', '✨', 
              '❌', '❣', '❤', '️', '🇦', '🇨', '🇪', '🇮', '🇳', '🇶', '🌁', '🌏', '🌷', '🌸', '🌹', '🌺', '🌻', '🍺', '🍻',
              '🎀', '🎁', '🎂', '🎇', '🎉', '🎖', '🎙', '🎤', '🎥', '🎧', '🎩', '🎬', '🎵', '🎶', '🎼', '🏁', '🏆',
              '🏵', '🏹', '🏻', '🏼', '🏾', '👆', '👇', '👈', '👉', '👋', '👌', '👍', '👎', '👏', '👑', '👒', '👔', '👕',
              '👖', '👠', '👦', '👧', '👨', '👩', '👪', '👫', '💃', '💄', '💋', '💌', '💍', '💎', '💐', '💓', '💔',
              '💕', '💖', '💗', '💘', '💙', '💚', '💛', '💜', '💝', '💞', '💢', '💥', '💪', '💯', '📌', '📍', '📚', 
              '📝', '🔝', '🔥', '🔪', '🔫', '🕉', '🕊', '🖤', '😀', '😁', '😂', '😃', '😄', '😅', '😆', '😇', 
              '😉', '😊', '😋', '😌', '😍', '😎', '😑', '😒', '😓', '😔', '😕', '😗', '😘', '😚', '😛', '😜', 
              '😝', '😞', '😟', '😠', '😡', '😢', '😣', '😤', '😥', '😩', '😫', '😭', '😮', '😰', '😱', '😲', 
              '😳', '😴', '😵', '😷', '😻', '🙂', '🙃', '🙄', '🙋', '🙌', '🙏', '🚒', '🚗', '🚩', '🚶', '🚹',
              '🛐', '🤐', '🤓', '🤔', '🤗', '🤘', '🤝', '🤞', '🤟', '🤡', '🤣', '🤦', '🤩', '🤪', '🤯', '🤳', 
              '🤴', '🤷', '🥀', '🥃', '🥇', '🥰', '🥳', '🥺', '🦁', '🧡']
       # text_nonpunct = [c for c in text if c not in string.punctuation]
        text_nonpunct ="".join([c for c in text if c not in msg])
        return text_nonpunct
    
r['cleaned'] = r['comclean'].apply(lambda x: clean_text(x))
r.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,LABEL,COMMENT,comclean,cleaned
0,EP,You are very beautiful.,You are very beautiful,You are very beautiful
2,EP,Nice,Nice,Nice
4,EP,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai
9,EP,Super,Super,Super
10,EP,Supar comedy,Supar comedy,Supar comedy

In [12]:
#create feture: message length
r['sen_len1'] = r['COMMENT'].apply(lambda x: len(x))
r.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,LABEL,COMMENT,comclean,cleaned,sen_len1
0,EP,You are very beautiful.,You are very beautiful,You are very beautiful,23
2,EP,Nice,Nice,Nice,4
4,EP,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai,41
9,EP,Super,Super,Super,5
10,EP,Supar comedy,Supar comedy,Supar comedy,12

In [13]:
#create feture: message length
r['sen_len2'] = r['comclean'].apply(lambda x: len(x))
r.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,LABEL,COMMENT,comclean,cleaned,sen_len1,sen_len2
0,EP,You are very beautiful.,You are very beautiful,You are very beautiful,23,22
2,EP,Nice,Nice,Nice,4,4
4,EP,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai,41,41
9,EP,Super,Super,Super,5,5
10,EP,Supar comedy,Supar comedy,Supar comedy,12,12

In [15]:
#create feture: message length
r['sen_len3'] = r['cleaned'].apply(lambda x: len(x))
r.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,LABEL,COMMENT,comclean,cleaned,sen_len1,sen_len2,sen_len3
0,EP,You are very beautiful.,You are very beautiful,You are very beautiful,23,22,22
2,EP,Nice,Nice,Nice,4,4,4
4,EP,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai,41,21,21
9,EP,Super,Super,Super,5,5,5
10,EP,Supar comedy,Supar comedy,Supar comedy,12,12,12

In [16]:
import re
def tokenize(txt):
    token = re.split('\s+',txt)
    return token

r['tokens'] = r['cleaned'].apply(lambda x: tokenize(x.lower()))
r.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,LABEL,COMMENT,comclean,cleaned,sen_len1,sen_len2,sen_len3,tokens
0,EP,You are very beautiful.,You are very beautiful,You are very beautiful,23,22,22,"[you, are, very, beautiful]"
2,EP,Nice,Nice,Nice,4,4,4,[nice]
4,EP,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai ðŸ˜ŠðŸ˜ŠðŸ¤£ðŸ‘‘ðŸ‘ˆ,Nice video jitu bhai,41,21,21,"[nice, video, jitu, bhai, ]"
9,EP,Super,Super,Super,5,5,5,[super]
10,EP,Supar comedy,Supar comedy,Supar comedy,12,12,12,"[supar, comedy]"

In [17]:
len(r['tokens'].sum())

10685

In [18]:
r.shape

(2401, 8)

In [ ]:
import pandas as pd
r = pd.read_excel('all6600.xlsx')
r.head()

# Hindi Labels Only

r =dataset[dataset['LABEL'].isin(['EP'])]
r.head()

import string
def clean_text(text):
       # text_nonpunct = [c for c in text if c not in string.punctuation]
        text_nonpunct ="".join([c for c in text if c not in string.punctuation])
        return text_nonpunct
    
r['comclean'] = r['COMMENT'].apply(lambda x: clean_text(x))
r.head()

from sklearn.feature_extraction.text import CountVectorizer
cv1 = CountVectorizer(analyzer=clean_text)

X = cv1.fit_transform(r['COMMENT'])
print(X.shape)

print(cv1.get_feature_names())

import string
def clean_text(text):
        msg =['\x81', '\x8d', '\x8f', '\x90', '\x9d', '\xa0', '¡', '¢', '£', '¤', '¥', '¦', '§', '¨', 'ª', 
              '«', '¬', '\xad', '®', '¯', '°', '²', '³', '´', 'µ', '¶', '·', '¸', '¹', 'º', '»', '¼', 
              '½', '¾', '¿', 'Ã', 'Å', 'Ç', 'Ì', '×', 'à', 'á', 'â', 'ä', 'ï', 'ð', 'ñ', 'ô', 'đ', 
              'ĺ', 'Œ', 'œ', 'Š', 'š', 'Ÿ', 'Ž', 'ž', 'ƒ', 'ˆ', '˜', '̽', '͓', 'ँ', 'ं', 'ः', 'अ', 
              'आ', 'इ', 'ई', 'उ', 'ऊ', 'ए', 'ऐ', 'ओ', 'औ', 'क', 'ख', 'ग', 'घ', 'च', 'छ', 'ज', 
              'झ', 'ट', 'ठ', 'ड', 'ढ', 'ण', 'त', 'थ', 'द', 'ध', 'न', 'प', 'फ', 'ब', 'भ', 'म', 'य',
              'र', 'ल', 'व', 'श', 'ष', 'स', 'ह', '़', 'ा', 'ि', 'ी', 'ु', 'ू', 'ृ', 'े', 'ै', 'ो', 'ौ', '्',
              'ज़', 'ड़', '।', 'ਂ', 'ਆ', 'ਕ', 'ਗ', 'ਜ', 'ਣ', 'ਦ', 'ਨ', 'ਪ', 'ਲ', 'ਵ', 'ਸ', 'ਹ', 'ਾ', 'ਿ',
              'ੂ', 'ੇ', 'ੈ', 'ੰ', 'ઁ', 'ં', 'ઃ', 'અ', 'આ', 'ઇ', 'ઈ', 'ઉ', 'ઊ', 'એ', 'ઐ', 'ઑ', 'ઓ', 'ક',
              'ખ', 'ગ', 'ઘ', 'ઙ', 'ચ', 'છ', 'જ', 'ઝ', 'ઞ', 'ટ', 'ઠ', 'ડ', 'ઢ', 'ણ', 'ત', 'થ', 'દ', 'ધ', 
              'ન', 'પ', 'ફ', 'બ', 'ભ', 'મ', 'ય', 'ર', 'લ', 'ળ', 'વ', 'શ', 'ષ', 'સ', 'હ', '઼', 'ા', 'િ', 'ી',
              'ુ', 'ૂ', 'ૃ', 'ૅ', 'ે', 'ૈ', 'ૉ', 'ો', 'ૌ', '્', 'ૐ', '૦', '૧', '૨', '૩', '૪', '૫', '૬', '૭', '૮', '૯', 
              '\u200c', '\u200d', '–', '—', '‘', '’', '‚', '“', '”', '„', '†', '‡', '•', '…', '‰', '‹', '›', '€', 
              '₹', '℅', '™', 'ℹ', '√', '☑', '☮', '☹', '☺', '♂', '♥', '⚔', '⚘', '⚰', '✌', '✍', '✨', 
              '❌', '❣', '❤', '️', '🇦', '🇨', '🇪', '🇮', '🇳', '🇶', '🌁', '🌏', '🌷', '🌸', '🌹', '🌺', '🌻', '🍺', '🍻',
              '🎀', '🎁', '🎂', '🎇', '🎉', '🎖', '🎙', '🎤', '🎥', '🎧', '🎩', '🎬', '🎵', '🎶', '🎼', '🏁', '🏆',
              '🏵', '🏹', '🏻', '🏼', '🏾', '👆', '👇', '👈', '👉', '👋', '👌', '👍', '👎', '👏', '👑', '👒', '👔', '👕',
              '👖', '👠', '👦', '👧', '👨', '👩', '👪', '👫', '💃', '💄', '💋', '💌', '💍', '💎', '💐', '💓', '💔',
              '💕', '💖', '💗', '💘', '💙', '💚', '💛', '💜', '💝', '💞', '💢', '💥', '💪', '💯', '📌', '📍', '📚', 
              '📝', '🔝', '🔥', '🔪', '🔫', '🕉', '🕊', '🖤', '😀', '😁', '😂', '😃', '😄', '😅', '😆', '😇', 
              '😉', '😊', '😋', '😌', '😍', '😎', '😑', '😒', '😓', '😔', '😕', '😗', '😘', '😚', '😛', '😜', 
              '😝', '😞', '😟', '😠', '😡', '😢', '😣', '😤', '😥', '😩', '😫', '😭', '😮', '😰', '😱', '😲', 
              '😳', '😴', '😵', '😷', '😻', '🙂', '🙃', '🙄', '🙋', '🙌', '🙏', '🚒', '🚗', '🚩', '🚶', '🚹',
              '🛐', '🤐', '🤓', '🤔', '🤗', '🤘', '🤝', '🤞', '🤟', '🤡', '🤣', '🤦', '🤩', '🤪', '🤯', '🤳', 
              '🤴', '🤷', '🥀', '🥃', '🥇', '🥰', '🥳', '🥺', '🦁', '🧡']
       # text_nonpunct = [c for c in text if c not in string.punctuation]
        text_nonpunct ="".join([c for c in text if c not in msg])
        return text_nonpunct
    
r['cleaned'] = r['comclean'].apply(lambda x: clean_text(x))
r.head()

#create feture: message length
r['sen_len1'] = r['COMMENT'].apply(lambda x: len(x))
r.head()

#create feture: message length
r['sen_len2'] = r['comclean'].apply(lambda x: len(x))
r.head()

#create feture: message length
r['sen_len3'] = r['cleaned'].apply(lambda x: len(x))
r.head()

import re
def tokenize(txt):
    token = re.split('\s+',txt)
    return token

r['tokens'] = r['cleaned'].apply(lambda x: tokenize(x.lower()))
r.head()

len(r['tokens'].sum())

r.shape